{"success": false, "error": "Traceback (most recent call last):\n  File \"/home/tiago/.local/lib/python3.6/site-packages/mythril/interfaces/cli.py\", line 816, in parse_args_and_execute\n    address = load_code(disassembler, args)\n  File \"/home/tiago/.local/lib/python3.6/site-packages/mythril/interfaces/cli.py\", line 610, in load_code\n    args.solidity_files\n  File \"/home/tiago/.local/lib/python3.6/site-packages/mythril/mythril/mythril_disassembler.py\", line 186, in load_from_solidity\n    solc_settings_json=self.solc_settings_json,\n  File \"/home/tiago/.local/lib/python3.6/site-packages/mythril/support/signatures.py\", line 245, in import_solidity_file\n    solc_json = get_solc_json(file_path, solc_binary, solc_settings_json)\n  File \"/home/tiago/.local/lib/python3.6/site-packages/mythril/ethereum/util.py\", line 66, in get_solc_json\n    p = Popen(cmd, stdin=PIPE, stdout=PIPE, stderr=PIPE)\n  File \"/usr/lib/python3.6/subprocess.py\", line 729, in __init__\n    restore_signals, start_new_session)\n  File \"/usr/lib/python3.6/subprocess.py\", line 1364, in _execute_child\n    raise child_exception_type(errno_num, err_msg, err_filename)\nPermissionError: [Errno 13] Permission denied: '/home/tiago/.py-solc/solc-v0.4.23/bin/solc'\n", "issues": []}
